### ISSUE TITLE
Why are these --hcp_Pipeline arguments necessary?

### ISSUE THREAD

**Issue by mharms** [humanconnectome/hcp-pipelines#3]
https://github.com/humanconnectome/hcp-pipelines/blob/b1d132913ec12203063d24ece48037e9417486b1/templates/structural/run_qunex.jinja2#L9

**Comment by mobalt** [comment]
I think I added this argument directly because for some reason the latest qunex wasn't getting the value from the `batch_parameters.txt`. If this has been fixed then it makes sense to remove directly passing it.
